### ISSUE TITLE
Roadmap to v0.1

### ISSUE THREAD

**Issue by uvchik** [oemof/feedinlib#64]
What needs to be done.

* [ ] Revise the docs -> #63 
* [ ] Revise example structure -> #61
* [ ] Check all issues (some are deprecated)
